### ISSUE TITLE
How to pass argument to method?

### ISSUE THREAD

**Issue by cyclops24** [quackware/meteor-waitOnServer#1]
Hi, First thanks for your awesome tutorial and guideline for meteor method with wait but I have a small question:

How to modify your util.js to accept input argument for method??

**Comment by curtislarson** [comment]
Hi cyclops24, I have updated the repository to include an optional `data` argument in the following commit:

3d748dbe19cd464d3334b3a70299bc45f6d641ac

**Comment by cyclops24** [comment]
Thanks for your attention. I test new version but it's only work with one argument and when I used with 3 argument it's only pass first argument to server method.

**Comment by curtislarson** [comment]
Hi cyclops24,

The commit 7b97095bef0455aceb260229aabd9d4d8dda3a0a should now allow you to pass multiple arguments.

**Comment by cyclops24** [comment]
Hi,
This is awesome. I tested your new commit and it's worked well.
Thanks quackware for your attention. Your tutorial and code save my time.
