### ISSUE TITLE
getResponse() always return first result

### ISSUE THREAD

**Issue by cyclops24** [quackware/meteor-waitOnServer#2]
Hi again @quackware ,
I found a small bug in multiple arguments mode.

If client call a server method many times with different argument getResponse always return first call result. I think this is because of getResponse function. Because this is always get result based on server method name.
For example:

``` javascript
Router.route('/post/:title', { name: "postByTitle" });

PostByTitleController = RouteController.extend({
    title: function(){
        var title = this.params.title;
        return title;
    },
    action: function () {
        this.render('postByTitle', {
            data: {
                listHtml: Util.getResponse("postByTitle")
            }
        });
    },
    waitOn: function () {
        return Util.waitOnServer("postByTitle", this.title());
    }
});
```

With this route if you fist go to **/post/title_1** and then go to **/post/title_2** route always render title_1 post content.

What's your idea?

**Comment by curtislarson** [comment]
Hi @cyclops24.

Check out 2a360b0d21b88727e633a3cc5a0a6be44420df06 and let me know if that fixes your problem.

**Comment by cyclops24** [comment]
Hi @quackware 
I use new version and problem fixed well.
Thanks for your attention man.
